services:
  trino:
    image: trinodb/trino
    volumes:
      - ./etc/trino/catalog:/etc/trino/catalog:rw
      - warehouse:/tmp/warehouse
    ports:
      - "8080:8080"
    links:
      - "db:database"
    environment:
      CATALOG_MANAGEMENT: dynamic

  db:
    image: postgres:17
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    volumes:
      - warehouse:/tmp/warehouse

volumes:
  pgdata:
  warehouse:
